# baseURL = 'https://ii.pk.edu.pl/~kswaldek/out'
baseURL = 'https://filipkrzysiekpk.github.io/'
languageCode = 'pl-pl'
title = 'Krzysztof Swałdek'
theme = 'stack'
staticDir = ['staticFiles']

defaultContentLanguage = "pl"

[markup]
  [markup.highlight]
    noClasses = false


[deployment]

[[deployment.targets]]
URL = "file://~kswaldek"
name = "mydeployment1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
#gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
#gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
#gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
#gzip = false

# Command:
# hugo deploy --force -s ../kswaldek