baseURL: 'https://filipkrzysiekpk.github.io/'
languageCode: pl-pl
title: Krzysztof Swałdek
theme: stack
staticDir:
  - staticFiles
defaultContentLanguage: pl
markup:
  highlight:
    noClasses: false
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2

deployment:
  targets:
    - URL: 'file://~kswaldek'
      name: mydeployment1
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
    - pattern: ^sitemap\.xml$
      contentType: application/xml
    - pattern: ^.+\.(html|xml|json)$

#gzip = false

# Command:
# hugo deploy --force -s ../kswaldek

params:
  footer:
      since: 2023
      customText:

  dateFormat:
      published: Jan 02, 2006
      lastUpdated: Jan 02, 2006 15:04 MST

  article:
    math: true
    toc: false
    readingTime: true

  widgets:

    page:
        - type: toc

  colorScheme:
      # Display toggle
      toggle: true

      # Available values: auto, light, dark
      default: auto

